config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers, :favorites
    end
  end
  resources :users do
  end
  resources :microposts, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  get '/hashtag/:name', to: "microposts#hashtag"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
  class User < ApplicationRecord
    has_many :microposts,dependent: :destroy
    has_many :active_relationships, class_name: "Relationship",
                            foreign_key: "follower_id",
                            dependent: :destroy
    has_many :passive_relationships, class_name: "Relationship",
                            foreign_key: "followed_id",
                            dependent: :destroy
    has_many :following, through: :active_relationships, source: :followed
    has_many :followers, through: :passive_relationships, source: :follower
    has_many :favorites, dependent: :destroy
    has_many :favorite_microposts, through: :favorites, source: :micropost
    attr_accessor :remember_token
    before_save { self.email = email.downcase}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :name,presence: true,length: {maximum: 50}
    validates :email,presence: true,length: {maximum: 255},
                format: { with: VALID_EMAIL_REGEX},
                uniqueness: {case_sensitive: false}
    has_secure_password
    validates :password, presence: true,length: {minimum: 6}, allow_nil: true

    def feed
      Micropost.where("user_id IN (:following_ids) OR user_id = :user_id",
       following_ids: following_ids, user_id: id)
    end
   

    def follow(other_user)
      following << other_user
    end

    def unfollow(other_user)
      active_relationships.find_by(followed_id: other_user.id).destroy
    end

    def following?(other_user)
      following.include?(other_user)
    end

    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
      SecureRandom.urlsafe_base64
    end

    def remember
      self.remember_token = User.new_token
      update_attribute(:remember_digest,User.digest(remember_token))
    end

    def authenticated?(remember_token)
      return false if remember_digest.nil?
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def forget
      update_attribute(:remember_digest, nil)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers, :favorites]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def following 
    @title = 'Following'
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = 'Followers'
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  def favorites
    @title = 'Favorite'
    @user = User.find(params[:id])
    @fav_microposts = @user.favorite_microposts.paginate(page: params[:page])
    render 'show_favorites'
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
        :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_url unless current_user? @user
    end

    def admin_user
      redirect_to root_url unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80)
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.slim
= form_for(current_user.active_relationships.build, remote: true) do |f|
  div
    = hidden_field_tag :followed_id, @user.id
  = f.submit "Follow", class: "btn btn-primary"

app/views/users/_follow_form.html.slim
- unless current_user?(@user)
  #follow_form
    - if current_user.following?(@user)
      = render 'unfollow'
    - else
      = render 'follow'

app/views/users/_form.html.slim
= form_for(@user, url: yield(:url)) do |f|
  = render 'shared/error_messages', object: f.object
  = f.label :name
  = f.text_field :name, class: 'form-control'
  = f.label :email
  = f.email_field :email, class: 'form-control'
  = f.label :password
  = f.password_field :password, class: 'form-control'
  = f.label :password_confirmation
  = f.password_field :password_confirmation, class: 'form-control'
  = f.submit yield(:button_text), class: "btn btn-primary"

app/views/users/_unfollow.html.slim
= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }, remote: true) do |f|
  = f.submit "Unfollow", class: "btn btn-success"

app/views/users/_user.html.slim
li
  = gravatar_for user, size: 50
  = link_to user.name, user
  - if current_user.admin? && !current_user?(user)
    |  | 
    = link_to "delete", user, method: :delete, data: { confirm: "You sure?" }

app/views/users/edit.html.slim
- provide(:title, 'Edit user')
- provide(:button_text, 'Save changes')
- provide(:url, user_path)
h1
  | Update your profile
.row
  .col-md-6.col-md-offset-3
    = render 'form'
    .gravatar_edit
      = gravatar_for @user
      a[href="http://gravatar.com/emails" target="_blank"]
        | Change

app/views/users/index.html.slim
- provide(:title, 'All users')
h1
  | All users
= will_paginate
ul.users
  = render @users
= will_paginate

app/views/users/new.html.slim
- provide(:title, 'Sign up')
- provide(:url, signup_path)
- provide(:button_text, 'Create my account')
h1
  | Sign up
.row
  .col-md-6.col-md-offset-3
    = render 'form'

app/views/users/show.html.slim
- provide(:title, @user.name)
.row
  aside.col-md-4
    section.user_info
      h1
        = gravatar_for @user
        = @user.name
    section.stats
      = render 'shared/stats'
  .col-md-8
    = render 'follow_form' if logged_in?
    - if @user.microposts.any?
      h3
        | Microposts (
        = @user.microposts.count
        | )
      ol.microposts
        = render @microposts
      = will_paginate @microposts

app/views/users/show_favorites.html.slim
- provide(:title, @title)
.row
  aside.col-md-4
    section.user_info
      = gravatar_for @user
      h1
        = @user.name
      span
        = link_to "view my profile", @user
      span
        b
          | Microposts:
        = @user.microposts.count
    section.stats
      = render 'shared/stats'
  .col-md-8
      h3
      = @title
      - if @fav_microposts.any?
      ol.microposts
          = render @fav_microposts
      = will_paginate @fav_microposts

app/views/users/show_follow.html.slim
- provide(:title, @title)
.row
  aside.col-md-4
    section.user_info
      = gravatar_for @user
      h1
        = @user.name
      span
        = link_to "view my profile", @user
      span
        b
          | Microposts:
        = @user.microposts.count
    section.stats
      = render 'shared/stats'
      - if @users.any?
        .user_avatars
          - @users.each do |user|
            = link_to gravatar_for(user, size: 30), user
  .col-md-8
    h3
      = @title
    - if @users.any?
      ul.users.follow
        = render @users
      = will_paginate